### ISSUE TITLE
meTypeset dying (gracefully) on 11075-36386-2-RV.doc

### ISSUE THREAD

**Issue by axfelix** [pkp/xmlps#43]
Document contains lots of in-progress change tracking, but that shouldn't necessarily be killing meTypeset; appears to die on a caption.

Output:

meTypeset output:
Recoverable error on line 169 of file:/var/www/var/documents/275/4786/metypeset/docx/from/lists.xsl:
FODC0005: java.io.FileNotFoundException:
/var/www/var/documents/275/4786/metypeset/docx/word/numbering.xml (No such file or directory)
Traceback (most recent call last):
File "vendor/MartinPaulEve/meTypeset/bin/meTypeset.py", line 252, in <module>
main()
File "vendor/MartinPaulEve/meTypeset/bin/meTypeset.py", line 248, in main
me_typeset_instance.run()
File "vendor/MartinPaulEve/meTypeset/bin/meTypeset.py", line 240, in run
self.run_modules()
File "vendor/MartinPaulEve/meTypeset/bin/meTypeset.py", line 215, in run_modules
cc.run_graphics()
File "/var/www/vendor/MartinPaulEve/meTypeset/bin/captionclassifier.py", line 303, in run_graphics
self.run_graphics_sibling()
File "/var/www/vendor/MartinPaulEve/meTypeset/bin/captionclassifier.py", line 145, in run_graphics_sibling
titles = parent.xpath('title')
AttributeError: 'NoneType' object has no attribute 'xpath'

**Comment by axfelix** [comment]
@sebastianmng might not be a bad idea to look into this at some point given how bad our caption numbers are -- this is one of the relatively few reliably crashes remaining in meTypeset.

**Comment by sebastianmng** [comment]
@axfelix  check out the fix [here](https://github.com/sebastianmng/meTypeset/commit/ab93e3ed5f9a50e40dfad6583429b7dd40128463).

**Comment by axfelix** [comment]
Closing -- these are tracked on meTypeset upstream.
